/**
 * 编辑器配置常量
 */

// 块类型定义
export const BLOCK_TYPES = {
  PARAGRAPH: "paragraph",
  HEADING_1: "heading-one",
  HEADING_2: "heading-two",
  HEADING_3: "heading-three",
  BULLET_LIST: "bulleted-list",
  NUMBERED_LIST: "numbered-list",
  TODO_LIST: "todo-list",
  QUOTE: "quote",
  CALLOUT: "callout",
  IMAGE: "image",
  VIDEO: "video",
  DIVIDER: "divider",
  TABLE: "table",
  EQUATION: "equation",
};

// 行内样式标记
export const MARKS = {
  BOLD: "bold",
  ITALIC: "italic",
  UNDERLINE: "underline",
  STRIKETHROUGH: "strikethrough",
  CODE: "code",
  LINK: "link",
  HIGHLIGHT: "highlight",
};

// 对齐方式
export const ALIGN_TYPES = {
  LEFT: "left",
  CENTER: "center",
  RIGHT: "right",
  JUSTIFY: "justify",
};

// Callout 类型
export const CALLOUT_TYPES = {
  INFO: "info",
  WARNING: "warning",
  ERROR: "error",
  SUCCESS: "success",
  QUOTE: "quote",
};

// 快捷键定义
export const HOTKEYS = {
  "mod+b": "bold",
  "mod+i": "italic",
  "mod+u": "underline",
  "mod+`": "code",
  "mod+shift+x": "strikethrough",
  "mod+k": "link",
  "mod+z": "undo",
  "mod+shift+z": "redo",
  "mod+y": "redo",
};

// Markdown 快捷输入规则
export const MARKDOWN_SHORTCUTS = [
  { pattern: /^#{1}\s$/, type: BLOCK_TYPES.HEADING_1 },
  { pattern: /^#{2}\s$/, type: BLOCK_TYPES.HEADING_2 },
  { pattern: /^#{3}\s$/, type: BLOCK_TYPES.HEADING_3 },
  { pattern: /^\*\s$/, type: BLOCK_TYPES.BULLET_LIST },
  { pattern: /^-\s$/, type: BLOCK_TYPES.BULLET_LIST },
  { pattern: /^1\.\s$/, type: BLOCK_TYPES.NUMBERED_LIST },
  { pattern: /^\[\s?\]\s$/, type: BLOCK_TYPES.TODO_LIST },
  { pattern: /^>\s$/, type: BLOCK_TYPES.QUOTE },
  { pattern: /^---$/, type: BLOCK_TYPES.DIVIDER },
];

// 斜杠命令菜单项
export const SLASH_COMMANDS = [
  {
    id: "text",
    title: "文本",
    icon: "📝",
    description: "普通文本段落",
    type: BLOCK_TYPES.PARAGRAPH,
    keywords: ["text", "paragraph", "p", "wenben"],
  },
  {
    id: "h1",
    title: "一级标题",
    icon: "H1",
    description: "大标题",
    type: BLOCK_TYPES.HEADING_1,
    keywords: ["heading", "h1", "title", "biaoti"],
  },
  {
    id: "h2",
    title: "二级标题",
    icon: "H2",
    description: "中标题",
    type: BLOCK_TYPES.HEADING_2,
    keywords: ["heading", "h2", "title", "biaoti"],
  },
  {
    id: "h3",
    title: "三级标题",
    icon: "H3",
    description: "小标题",
    type: BLOCK_TYPES.HEADING_3,
    keywords: ["heading", "h3", "title", "biaoti"],
  },
  {
    id: "bullet",
    title: "无序列表",
    icon: "•",
    description: "创建无序列表",
    type: BLOCK_TYPES.BULLET_LIST,
    keywords: ["bullet", "list", "ul", "liebiao"],
  },
  {
    id: "numbered",
    title: "有序列表",
    icon: "1.",
    description: "创建有序列表",
    type: BLOCK_TYPES.NUMBERED_LIST,
    keywords: ["numbered", "list", "ol", "liebiao"],
  },
  {
    id: "todo",
    title: "待办列表",
    icon: "☑",
    description: "创建待办事项",
    type: BLOCK_TYPES.TODO_LIST,
    keywords: ["todo", "checkbox", "task", "daiban"],
  },
  {
    id: "quote",
    title: "引用",
    icon: "💬",
    description: "插入引用块",
    type: BLOCK_TYPES.QUOTE,
    keywords: ["quote", "blockquote", "yinyong"],
  },
  {
    id: "callout",
    title: "提示框",
    icon: "💡",
    description: "插入提示信息框",
    type: BLOCK_TYPES.CALLOUT,
    keywords: ["callout", "notice", "alert", "tishi"],
  },
  {
    id: "image",
    title: "图片",
    icon: "🖼️",
    description: "上传或插入图片",
    type: BLOCK_TYPES.IMAGE,
    keywords: ["image", "picture", "photo", "tupian"],
  },
  {
    id: "video",
    title: "视频",
    icon: "🎬",
    description: "插入视频",
    type: BLOCK_TYPES.VIDEO,
    keywords: ["video", "shipin", "media"],
  },
  {
    id: "divider",
    title: "分割线",
    icon: "—",
    description: "插入分割线",
    type: BLOCK_TYPES.DIVIDER,
    keywords: ["divider", "hr", "line", "fengexian"],
  },
  {
    id: "table",
    title: "表格",
    icon: "📊",
    description: "插入表格",
    type: BLOCK_TYPES.TABLE,
    keywords: ["table", "biaoge", "grid"],
  },
  {
    id: "equation",
    title: "公式",
    icon: "∑",
    description: "插入数学公式",
    type: BLOCK_TYPES.EQUATION,
    keywords: ["equation", "math", "latex", "gongshi"],
  },
];

// 颜色选择器预设颜色
export const PRESET_COLORS = [
  "#000000",
  "#434343",
  "#666666",
  "#999999",
  "#B7B7B7",
  "#CCCCCC",
  "#D9D9D9",
  "#EFEFEF",
  "#F3F3F3",
  "#FFFFFF",
  "#980000",
  "#FF0000",
  "#FF9900",
  "#FFFF00",
  "#00FF00",
  "#00FFFF",
  "#4A86E8",
  "#0000FF",
  "#9900FF",
  "#FF00FF",
  "#E6B8AF",
  "#F4CCCC",
  "#FCE5CD",
  "#FFF2CC",
  "#D9EAD3",
  "#D0E0E3",
  "#C9DAF8",
  "#CFE2F3",
  "#D9D2E9",
  "#EAD1DC",
  "#DD7E6B",
  "#EA9999",
  "#F9CB9C",
  "#FFE599",
  "#B6D7A8",
  "#A2C4C9",
  "#A4C2F4",
  "#9FC5E8",
  "#B4A7D6",
  "#D5A6BD",
  "#CC4125",
  "#E06666",
  "#F6B26B",
  "#FFD966",
  "#93C47D",
  "#76A5AF",
  "#6D9EEB",
  "#6FA8DC",
  "#8E7CC3",
  "#C27BA0",
  "#A61C00",
  "#CC0000",
  "#E69138",
  "#F1C232",
  "#6AA84F",
  "#45818E",
  "#3C78D8",
  "#3D85C6",
  "#674EA7",
  "#A64D79",
  "#85200C",
  "#990000",
  "#B45F06",
  "#BF9000",
  "#38761D",
  "#134F5C",
  "#1155CC",
  "#0B5394",
  "#351C75",
  "#733554",
  "#5B0F00",
  "#660000",
  "#783F04",
  "#7F6000",
  "#274E13",
  "#0C343D",
  "#1C4587",
  "#073763",
  "#20124D",
  "#4C1130",
];

export default {
  BLOCK_TYPES,
  MARKS,
  ALIGN_TYPES,
  CALLOUT_TYPES,
  HOTKEYS,
  MARKDOWN_SHORTCUTS,
  SLASH_COMMANDS,
  PRESET_COLORS,
};
